name: FooCI

on:
  push:
    branches:
      - main

env:
  Foo: bar


jobs:
  test:
    env:
      Bar: baz
    runs-on: ubuntu-latest
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: DB
        run: |
          npx get-db --yes
